export const types = {
  GET_USER_DATA: "GET_USER_DATA",
  GET_ALL_PRODUCTS: "GET_ALL_PRODUCTS",
  GET_PRODUCTS_HISTORY: "GET_PRODUCTS_HISTORY",
  PRODUCT_REDEEM: "PRODUCT_REDEEM",
  PRODUCT_POINTS: "PRODUCT_POINTS",
  PRODUCT_POINTS_PLUS: "PRODUCT_POINTS_PLUS",
  RESET_STATE: "RESET_STATE",
  SET_LOADING: "SET_LOADING",
};
